amamba:
  - "docs/en/docs/amamba/**/*"
  - "docs/zh/docs/amamba/**/*"

blogs:
  - "docs/en/docs/blogs/**/*"
  - "docs/zh/docs/blogs/**/*"

dce:
  - "docs/en/docs/dce/**/*"
  - "docs/zh/docs/dce/**/*"

download:
  - "docs/en/docs/download/**/*"
  - "docs/zh/docs/download/**/*"

eco:
  - "docs/en/docs/community/**/*"
  - "docs/zh/docs/community/**/*"

ghippo:
  - "docs/en/docs/ghippo/**/*"
  - "docs/zh/docs/ghippo/**/*"

hydra:
  - "docs/en/docs/hydra/**/*"
  - "docs/zh/docs/hydra/**/*"

insight:
  - "docs/en/docs/insight/**/*"
  - "docs/zh/docs/insight/**/*"

installer:
  - "docs/en/docs/install/**/*"
  - "docs/zh/docs/install/**/*"

kairship:
  - "docs/en/docs/kairship/**/*"
  - "docs/zh/docs/kairship/**/*"

kangaroo:
  - "docs/en/docs/kangaroo/**/*"
  - "docs/zh/docs/kangaroo/**/*"

kant:
  - "docs/en/docs/kant/**/*"
  - "docs/zh/docs/kant/**/*"

kpanda:
  - "docs/en/docs/kpanda/**/*"
  - "docs/zh/docs/kpanda/**/*"

midware:
  - "docs/en/docs/middleware/**/*"
  - "docs/zh/docs/middleware/**/*"

mspider:
  - "docs/en/docs/mspider/**/*"
  - "docs/zh/docs/mspider/**/*"

native:
  - "docs/en/docs/native/**/*"
  - "docs/zh/docs/native/**/*"

network:
  - "docs/en/docs/network/**/*"
  - "docs/zh/docs/network/**/*"

skoala:
  - "docs/en/docs/skoala/**/*"
  - "docs/zh/docs/skoala/**/*"

storage:
  - "docs/en/docs/storage/**/*"
  - "docs/zh/docs/storage/**/*"

trial:
  - "docs/en/docs/trial/**/*"
  - "docs/zh/docs/trial/**/*"

videos:
  - "docs/en/docs/videos/**/*"
  - "docs/zh/docs/videos/**/*"

virtnest:
  - "docs/en/docs/virtnest/**/*"
  - "docs/zh/docs/virtnest/**/*"

topohub:
  - "docs/en/docs/topohub/**/*"
  - "docs/zh/docs/topohub/**/*"

en:
  - "docs/en/**/*"

zh:
  - "docs/zh/**/*"

develop:
  - "scripts/**/*"
  - ".github/**/*"

i18n:
  - "docs/en/**/*"

baize:
  - "docs/en/docs/baize/**/*"
  - "docs/zh/docs/baize/**/*"
