blank_issues_enabled: false
contact_links:
  - name: ✅ Connect US when your having questions.
    url: https://www.daocloud.io
    about: If you have questions about DaoCloud product or need support building applicaion, please ask us