-apiVersion: apiextensions.k8s.io/v1beta1
apiVersion: apiextensions.k8s.io/v1
@@ -10,1 +10,1 @@
-kind: CustomResourceDefinition
kind: CustomResourceDefinition
@@ -20,1 +20,1 @@
-  version: v1beta1
  version: v1