name: Check Compatibility Links

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v8.1.0

      - run: make sync-link-check

      - run: make check-links
        env:
          DOCS_BASE_URL: "https://docs.daocloud.io"

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Compatibility Links Check Report'
          content-filepath: ./check-results.txt
          labels: |
            report
            automated-check
