name: Gemini AI Code Reviewer
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    if: >
      (github.event.issue.pull_request != null || github.event.pull_request != null) &&
      contains(github.event.comment.body, '/gemini-review')
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install gh -y

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: pr
        run: |
          PR_NUMBER=${{ github.event.issue.number || github.event.pull_request.number }}
          PR_JSON=$(gh api repos/${{ github.repository }}/pulls/${PR_NUMBER})
          echo "head_sha=$(echo $PR_JSON | jq -r .head.sha)" >> $GITHUB_OUTPUT
          echo "base_sha=$(echo $PR_JSON | jq -r .base.sha)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: truongnh1992/gemini-ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-pro-preview-05-06
          EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
