# This is a basic workflow to help you get started with Actions

name: find corrupted hyperlink

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for mkdocs to be able to display pages last update info
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Runs a single command using the runners shell
      - run: pip install mkdocs-material \
              mkdocs-git-revision-date-plugin \
              mkdocs-mermaid2-plugin \
              mkdocs-rss-plugin \
              mkdocs-minify-plugin \
              mkdocs-macros-plugin \
              mkdocs-git-revision-date-localized-plugin \
              mkdocs-awesome-pages-plugin \
              mkdocs-redirects \
              mkdocs-print-site-plugin \
              mkdocs-swagger-ui-tag \
              pyyaml
      
      # add custom plugin with pdf support
      - run: pip install git+https://github.com/SAMZONG/mkdocs-with-pdf-support-material-v8

      # check corrupted hyperlink
      - run: pwd
      - run: mkdocs build -f docs/zh/mkdocs.yml -d ../../public/  >> zh_build.log
      - run: mkdocs build -f docs/en/mkdocs.yml -d ../../public/en/ >> en_build.log
      - run: ls -lha
      - run: echo "# zh_build.log" >> issue-body.txt
      - run: grep -e 'WARNING.*\.md.*contains a link to.*not found' zh_build.log >> issue-body.txt
      - run: echo "# en_build.log" >> issue-body.txt
      - run: grep -e 'WARNING.*\.md.*contains a link to.*not found' en_build.log >> issue-body.txt

      # Create an issue if there are any warnings
      - name: Create issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: 'Corrupted document hyperlink'
          body: |
            ${{ steps.get_issue_body.outputs.body }}
          labels: |
            bug
            corrupted-hyperlink
          assignees: |
            windsonsea
            Michelle951
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY_PATH: ./issue-body.txt
        id: get_issue_body