name: find corrupted hyperlink

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v8.1.0

      - run: make sync

      - run: make build zh > zh_build.log 2>&1
      - run: make build en > en_build.log 2>&1
      - run: ls -lha
      - run: echo "# zh_build.log" >> issue-body.txt
      - run: grep -E 'WARNING.*\.md.*contains a link .*not found' zh_build.log >> issue-body.txt
      - run: echo "# en_build.log" >> issue-body.txt
      - run: grep -E 'WARNING.*\.md.*contains a link .*not found' en_build.log >> issue-body.txt

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: 'Corrupted document hyperlink'
          body: |
            ${{ steps.get_issue_body.outputs.body }}
          labels: |
            bug
            corrupted-hyperlink
          assignees: |
            windsonsea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY_PATH: ./issue-body.txt
        id: get_issue_body
