name: deploy-for-main-path

on:
  workflow_dispatch:

env:
  UCLOUD_PUBLICKEY : ${{ secrets.UCLOUD_PUBLICKEY }}
  UCLOUD_PRIVATEKEY : ${{ secrets.UCLOUD_PRIVATEKEY }}
  UCLOUD_REGION : ${{ secrets.UCLOUD_REGION }}
  UCLOUD_BUCKET : ${{ secrets.UCLOUD_BUCKET }}
  CI: 1

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout OpenAPI docs
        uses: actions/checkout@v4
        with:
          repository: daocloud/daocloud-api-docs
          path: dao-openapi
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v8.1.0

      - run: make sync-upload

      - run: make merge-openapi-docs

      - run: make build-path all

      - run: make upload-ucloud

      - run: make refresh-cdn-cache
