name: deploy-for-main

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  workflow_dispatch:

env:
  UCLOUD_PUBLICKEY : ${{ secrets.UCLOUD_PUBLICKEY }}
  UCLOUD_PRIVATEKEY : ${{ secrets.UCLOUD_PRIVATEKEY }}
  UCLOUD_REGION : ${{ secrets.UCLOUD_REGION }}
  UCLOUD_BUCKET : ${{ secrets.UCLOUD_BUCKET }}
  CI: 1

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout OpenAPI docs
        uses: actions/checkout@v4
        with:
          repository: daocloud/daocloud-api-docs
          path: dao-openapi
          fetch-depth: 0

      - name: Checkout download docs
        uses: actions/checkout@v4
        with:
          repository: daocloud/daocloud-download-docs
          path: daocloud-download-docs
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v8.1.0

      - run: make sync

      - run: make merge-external-docs

      - run: make build all

      - name: Upload to Qiniu Kodo
        uses: samzong/action-qiniu-upload-nodejs@v0.0.8
        with:
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}
          bucket: ${{ secrets.QINIU_BUCKET }}
          source_dir: public
          dest_dir: /
          concurrency: 50
